### ISSUE TITLE
Start class error

### ISSUE THREAD

**Issue by ghost** [Th3K1n91/mega_nz-Creator#1]
Hi, when I try to generate some accounts the program freezes and the terminal spam "Retrying, start  class error". How can I fix that?

![alt text](https://i.ibb.co/Dtm8PN7/unknown.png)

**Comment by Th3K1n91** [comment]
Do you have the latest commit?

**Comment by Th3K1n91** [comment]
Should be fixed now.

Try it yourself and close the Issue if there's nothing more.
