### ISSUE TITLE
Register ERROR

### ISSUE THREAD

**Issue by Ognisty321** [Th3K1n91/mega_nz-Creator#2]
Seems like a problem with the email domain?

`start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR
start class error
Retrying
Register ERROR`

**Comment by Th3K1n91** [comment]
**Version 5 is released now!**
I think it fixed your issue.

To your question about the email domain:
In rare cases, the email provider is sending their requests slowly.
If that's the case, the bot is waiting an **unlimited** time till the request goes through.
(This will be fixed on the next [xitroo_api](https://github.com/Th3K1n91/xitroo_api) release)
