### ISSUE TITLE
always getting ERROR: Invalid verification link or key: 'None'

### ISSUE THREAD

**Issue by Milincho** [Th3K1n91/mega_nz-Creator#3]
always getting ERROR: Invalid verification link or key: 'None'

![09dlB92](https://user-images.githubusercontent.com/60118859/186931626-300b3bb3-7052-47cd-9142-fea34b6e7d2f.png)

**Comment by Milincho** [comment]
Same with either the Win executable version or the Python version:

![image](https://user-images.githubusercontent.com/60118859/186946531-587d82ba-3d62-455f-be61-23d63d9aed3e.png)

**Comment by Th3K1n91** [comment]
Download the newest python version. I think it should be fixed now.

The Issue was the Language from the inbox.

**Comment by Th3K1n91** [comment]
WIN-EXE Version is now updated too.

**Comment by Milincho** [comment]
> WIN-EXE Version is now updated too.

Ah, thank you very much, man. Now it works. :-)

**Comment by Milincho** [comment]
The ERROR: Invalid verification link or key: 'None' is back...

![image](https://user-images.githubusercontent.com/60118859/187980285-7eb319a4-3fd5-4192-baaa-8e40619afe8c.png)

**Comment by Th3K1n91** [comment]
@Milincho you don't use the latest version.
V5.3.0 should say in the bottom left corner.

**Comment by Milincho** [comment]
> @Milincho you don't use the latest version. V5.3.0 should say in the bottom left corner.

Ah, right. Sorry I forgot to update in this other machine. Thanks.
