### ISSUE TITLE
The program stopped working: "[Xitroo] HTTP Error" and then "ERROR: Invalid verification link or key: 'None'

### ISSUE THREAD

**Issue by Milincho** [Th3K1n91/mega_nz-Creator#4]
Doesn't work now. It says: "[Xitroo] HTTP Error" and then "ERROR: Invalid verification link or key: 'None'

![image](https://github.com/Th3K1n91/mega_nz-Creator/assets/60118859/5eae4ef7-92fc-4d75-84f4-ddc4a7b3ecf5)

**Comment by Th3K1n91** [comment]
Looks like you got rate limited by Xitroo.

Try to open https://xitroo.de and tell me if it worked

**Comment by Milincho** [comment]
Yes. The web site works ok.

![image](https://github.com/Th3K1n91/mega_nz-Creator/assets/60118859/97539fa8-7c64-468f-948a-d0824afebf08)

**Comment by Milincho** [comment]
It's working again now. Thanks.

**Comment by Milincho** [comment]
It doesn't work again. Same problem: "Bad Request". 

![image](https://github.com/Th3K1n91/mega_nz-Creator/assets/60118859/24bad4ff-487c-44e8-8701-7462240842d9)

Web access works ok:
![image](https://github.com/Th3K1n91/mega_nz-Creator/assets/60118859/30d1c3d9-62f8-48b5-b249-d9c56b538447)
